// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Data 应用设置
 */
export class Data {
    /**
     * Creates a new Data instance.
     * @param {Partial<Data>} [$$source = {}] - The source object to create the Data.
     */
    constructor($$source = {}) {
        if (!("hotkey" in $$source)) {
            /**
             * "Alt+E"
             * @member
             * @type {string}
             */
            this["hotkey"] = "";
        }
        if (!("auto_start" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["auto_start"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Data instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Data}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Data(/** @type {Partial<Data>} */($$parsedSource));
    }
}
