// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 设置服务，管理设置读写
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings 返回当前设置的副本
 * @returns {$CancellablePromise<$models.Data>}
 */
export function GetSettings() {
    return $Call.ByID(3800254777).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Load 从磁盘读取设置，失败时使用默认值；首次加载会初始化默认站点条目
 * @returns {$CancellablePromise<void>}
 */
export function Load() {
    return $Call.ByID(1135572900);
}

/**
 * MarkScriptsReleased 标记内置脚本已释放
 * @returns {$CancellablePromise<void>}
 */
export function MarkScriptsReleased() {
    return $Call.ByID(3289886496);
}

/**
 * OnSave 注册保存后的回调（用于热键重新注册）
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function OnSave(fn) {
    return $Call.ByID(477033444, fn);
}

/**
 * OpenScriptDir 用资源管理器打开脚本目录
 * @param {string} dirName
 * @returns {$CancellablePromise<void>}
 */
export function OpenScriptDir(dirName) {
    return $Call.ByID(2083207762, dirName);
}

/**
 * Save 将当前设置写入磁盘。
 * 使用 RLock 因为只读取 s.data（json.MarshalIndent 是纯读操作），
 * 磁盘写入（os.WriteFile）不涉及共享内存，不需要写锁。
 * @returns {$CancellablePromise<void>}
 */
export function Save() {
    return $Call.ByID(3860823493);
}

/**
 * SaveSettings 更新并持久化设置，保存后触发回调
 * @param {$models.Data} d
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(d) {
    return $Call.ByID(1099196200, d);
}

/**
 * ScriptDir 返回指定条目的脚本绝对路径
 * @param {string} dirName
 * @returns {$CancellablePromise<string>}
 */
export function ScriptDir(dirName) {
    return $Call.ByID(3106217562, dirName);
}

// Private type creation functions
const $$createType0 = $models.Data.createFrom;
