// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service 设置服务，管理设置读写和热键变更回调
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetSettings 返回当前设置的副本（供前端调用）
 * @returns {$CancellablePromise<$models.Data>}
 */
export function GetSettings() {
    return $Call.ByID(3800254777).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Load 从磁盘读取设置，失败时使用默认值
 * @returns {$CancellablePromise<void>}
 */
export function Load() {
    return $Call.ByID(1135572900);
}

/**
 * OnHotkeyChange 注册热键变更回调。回调返回 error 则会拒绝此次修改。
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function OnHotkeyChange(fn) {
    return $Call.ByID(1459005827, fn);
}

/**
 * Save 将当前设置写入磁盘
 * @returns {$CancellablePromise<void>}
 */
export function Save() {
    return $Call.ByID(3860823493);
}

/**
 * SaveSettings 更新并持久化设置。如果热键变更，先验证新热键有效性。
 * @param {$models.Data} d
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(d) {
    return $Call.ByID(1099196200, d);
}

// Private type creation functions
const $$createType0 = $models.Data.createFrom;
